FROM eclipse-temurin:17.0.5_8-jdk

USER root
RUN apt update
RUN apt -y upgrade
RUN apt install -y locales
RUN sed -i '/ja_JP.UTF-8/s/^# //g' /etc/locale.gen
RUN locale-gen

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8
ENV TZ Asia/Tokyo

COPY build/libs/testcontainer-spring-demo-2022.12.jar /app.jar

ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 8080