version: '3'
services:
  postgres:
    image: postgres:11.10-alpine
    # 任意のパスワード
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    # ホスト側は任意のディレクトリ
    volumes:
      - ./data:/var/lib/postgresql/data
    # ホスト側は任意のポート
    ports:
      - 5432:5432