version: '3'
services:
  postgres:
    image: postgres:15-bullseye
    # 任意のパスワード
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    # ホスト側は任意のディレクトリ
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    # ホスト側は任意のポート
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      spring.profiles.active: local
      spring.datasource.url: jdbc:postgresql://postgres:5432/main
    volumes:
      - ./config:/config
    ports:
      - "8080:8080"
    depends_on:
      - postgres